# Generated by Django 5.2 on 2025-04-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('roof_size', models.IntegerField()),
                ('roof_type', models.CharField(choices=[('Metal', 'Metal'), ('TPO', 'TPO'), ('Foam', 'Foam'), ('EPDM', 'EPDM'), ('Built-up', 'Built-up'), ('Modified Bitumen', 'Modified Bitumen'), ('PVC', 'PVC'), ('Other', 'Other')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('project_date', models.DateField()),
            ],
        ),
    ]
