# Generated by Django 5.2 on 2025-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='roof_type',
            field=models.CharField(choices=[('METAL', 'Metal'), ('TPO', 'TPO'), ('FOAM', 'Foam'), ('EPDM', 'EPDM'), ('BUILT-UP', 'Built-up'), ('MODIFIED BITUMEN', 'Modified Bitumen'), ('PVC', 'PVC'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
